version: '2'

services:
  pg:
      image: postgres
      ports:
      - "5432:5432"
      volumes:
      - pg_volume:/var/lib/postgresql/data
  db:
      image: mysql
      ports:
      - "3306:3306"
      environment:
          MYSQL_ROOT_PASSWORD: secret 
          MYSQL_DB: flask_api 
          MYSQL_USER: flask_api
          MYSQL_PASSWORD: 9eMJPrJQAJnmooUlDWH3OsKrKLM 
      volumes:
      - mysql_volume:/var/lib/mysql
  redis:
      image: redis
      ports:
      - "6379:6379"
volumes:
  mysql_volume:
  pg_volume:
